YunjiWeb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('web.urls')),
    url(r'mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from . import views

app_name = 'web'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'aboutus', views.aboutus, name='aboutus'),
    url(r'aboutrange', views.aboutrange, name='aboutrange'),
    url(r'aboutyunji', views.aboutyunji, name='aboutyunji'),
    url(r'service', views.service, name='service'),
    url(r'sereva', views.sereva, name='sereva'),
    url(r'serproduction', views.serproduction, name='serproduction'),
    url(r'serask', views.serask, name='serask'),
    url(r'serdes', views.serdes, name='serdes'),
    # url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'contact', views.contact, name='contact'),
]

web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from mdeditor.fields import MDTextField
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('标题', max_length=70)

    body = MDTextField('正文')

    created_time = models.DateTimeField('创建时间', default=timezone.now)
    modified_time = models.DateTimeField('修改时间')

    excerpt = models.CharField('摘要', max_length=200, blank=True) # 文章摘要

    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)

    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('web:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

web/views.py
import markdown

from django.shortcuts import render, get_object_or_404
from .models import Post, Category 
from django.views.generic import ListView # 类视图函数
from pure_pagination.mixins import PaginationMixin

# Create your views here.
 
def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'web/index.html', context={'post_list': post_list})

def detail(request, pk): 
    post = get_object_or_404(Post, pk=pk) # 得到文章
    post.body = markdown.markdown(post.body, extensions=['markdown.extensions.extra', 
                                                        'markdown.extensions.codehilite',
                                                        'markdown.extensions.toc',
                                                        'markdown.extensions.tables',])

    cate = post.category # 得到分类名
    
    """
    筛选该分类名的所有文章，倒序排列
    查询上一篇文章
    """
    post_pre_lst = Post.objects.filter(category=cate).filter(id__lt=pk)
    post_next_lst = Post.objects.filter(category=cate).filter(id__gt=pk)
   
    if post_pre_lst.exists():
      post_pre = post_pre_lst.order_by('-created_time').first()
    else:
      post_pre = post

    if post_next_lst.exists():
      post_next = post_next_lst.order_by('-created_time').last()
    else:
      post_next = post

    return render(request, 'web/detail.html', context={'post': post, 'post_pre':post_pre, 'post_next':post_next})

def aboutus(request):
    return render(request, 'web/aboutus.html')

def aboutrange(request):
    return render(request, 'web/aboutrange.html')

def aboutyunji(request):
    return render(request, 'web/aboutyunji.html')

def service(request):
    return render(request, 'web/service.html')

def sereva(request):
    return render(request, 'web/sereva.html')

def serproduction(request):
    return render(request, 'web/serproduction.html')

def serask(request):
    return render(request, 'web/serask.html')

def serdes(request):
    return render(request, 'web/serdes.html')

"""def category(request, pk): 
    # 成功案例、新闻资讯、文件下赞、项目公示的文章列表
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'web/category.html', context={'post_list': post_list})"""

class CategoryView(PaginationMixin, ListView):
    model = Post
    template_name = 'web/category.html'
    context_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 10

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate).order_by('-created_time')

def contact(request):
    return render(request, 'web/contact.html')

templates/base.html
{% load staticfiles %}
{% load web_tags %}

<!doctype html>
<html>

<head>
  <!-- meta -->
  <meta charset="utf-8">
  <title>西安云际环保科技有限公司</title>

  <!-- css -->
  <link href="{% static 'web/css/base.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'web/css/index_content.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'web/css/other_content.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'web/css/editormd.css' %}" rel="stylesheet" type="text/css">
</head>

<body>

  <!--logo-->
  <div class="web-width"><img src="{% static 'web/images/logo.jpg' %}" width="1000" height="115" alt="" /></div>


  <!-- 导航栏 begin -->
  <div class="nav">
    <div class="web-width">
      <ul class="nav-item" style="position:relative; margin:0px; padding-left: 4px;">
        <li><a href="{% url 'web:index' %}">首&nbsp;&nbsp;&nbsp;页</a></li>
        <li><a href="{% url 'web:aboutus' %}">公司简介</a></li>
        <li><a href="{% url 'web:service' %}">服务项目</a></li>
        <li><a href="{% url 'web:category' pk=2 %}">成功案例</a></li>
        <li><a href="{% url 'web:category' pk=5 %}">项目公示</a></li>
        <li><a href="{% url 'web:category' pk=3 %}">行业资讯</a></li>
        <li><a href="{% url 'web:category' pk=4 %}">文件下载</a></li>
        <li><a href="{% url 'web:contact' %}">联系我们</a></li>
      </ul>
    </div>
  </div>
  <!-- 导航栏 end -->


  <!--网页内容部分 begin -->
  <div class="web-width">

    <!-- 轮播图片
			<div class="photo-box">
				<ul class="photo-ul" id="photo-ul" style="list-style: none; margin: 0; padding: 0;"> 
					<li><img src="{% static 'web/images/photo-box03.jpg' %}" width="1000" height="314" /></li>
					<li><img src="{% static 'web/images/photo-box01.jpg' %}" width="1000" height="314" /></li>
					<li><img src="{% static 'web/images/photo-box02.jpg' %}" width="1000" height="314" /></li>
				</ul>
				 左右切换 
				<div class="left-botton indexs" id="left-botton">&lt;</div>
				<div class="right-botton indexs" id="right-botton">&gt;</div>	
			</div> -->

    <!-- js 
			<script type="text/javascript">	
				var imgs = document.getElementById("photo-ul").children; // 找到所有轮播li
				var leftbotton = document.getElementById("left-botton");
				var rightbotton = document.getElementById("right-botton");
				var index = 0;
				var dingshiqi;
				chongqi();
				function chongqi(){
					dingshiqi = setInterval(function(){
						index++;
						if(index==imgs.length){
							index=0;
						}
						for(var i=0;i<imgs.length;i++){
							imgs[i].style.cssText="z-index:0;";
						}
						imgs[index].style.cssText="z-index:100;";
					},5000);
				}
				leftbotton.onclick=function(){
					clearInterval(dingshiqi);
					index--;
					if(index<0){
						index=imgs.length-1;
					}
					for(var i=0;i<imgs.length;i++){
						imgs[i].style.cssText="z-index:0;";
					}
					imgs[index].style.cssText="z-index:100;";
					chongqi();
				}
				rightbotton.onclick=function(){
					clearInterval(dingshiqi);
					index++;
					if(index>imgs.length-1){
						index=0;
					}
					for(var i=0;i<imgs.length;i++){
						imgs[i].style.cssText="z-index:0;";
					}
					imgs[index].style.cssText="z-index:100;";
					chongqi();
				}
			</script>-->

    <!-- 内容填充  begin -->
    {% block main %}
    {% endblock main %}
    <!-- 内容填充  end -->

  </div>
  <!--网页内容部分 end -->


  <!-- 网页底部信息 begin -->
  <div class="cl"></div>
  <div class="web-blank"></div>
  <div class="foot">
    <div class="web-width">
      <div class="foot-content">
        <br>
        地址：西安市新城区解放路77号裕郎国际1幢1321室&nbsp;&nbsp;&nbsp;&nbsp;电话：15829617767&nbsp;&nbsp;&nbsp;&nbsp;网址：www.xayunjihb.cn <br>
        CopyRight&nbsp;&nbsp;xayunjihb.cn&nbsp;版权所有&nbsp;©2020-2021 All Rights
        Reserved.&nbsp;&nbsp;&nbsp;&nbsp;陕ICP备200112704号
      </div>
    </div>
  </div>
  <!-- 网页底部信息 end -->

  <!-- <script src="{% static 'web\js\jquery.min.js' %}"> </script>
		<script>
			$(function(){
				$('.photo-box ul li img').eq(1).hide();
				$('.photo-box ul li img').eq(2).hide();
			});
			$(".nav-item li a").click(function(){
				var text=	$(this).text();
				if(text="服务项目")	{
					$('.photo-box ul li img').eq(1).show();
					$('.photo-box ul li img').eq(0).hide();
					$('.photo-box ul li img').eq(2).hide();
				}
			}); 
			
    </script>-->
  <script src="{% static 'web\js\jquery.min.js' %}"> </script>
  <script src="{% static 'web\js\prettify.min.js' %}"> </script>
  <script src="{% static 'web\js\marked.min.js' %}"> </script>
  <script src="{% static 'web\js\editormd.js' %}"> </script>

</body>

</html>

templates/web/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load web_tags %}

{% block main %}

<!-- 轮播图片-->
<div class="photo-box">
	<ul class="photo-ul" id="photo-ul" style="list-style: none; margin: 0; padding: 0;"> 
		<li><img src="{% static 'web/images/photo-box03.jpg' %}" width="1000" height="314" /></li>
	</ul>
</div>

<!--公司简介-->
<div>
	<!--头部-->
	<div class="title-long">
		<div class="left-title"><img src="{% static 'web/images/presentation.gif' %}" width="194" height="25" alt=""/></div>
		<div class="right-title"><a href="{% url 'web:aboutus' %}">更多&nbsp;&gt;&gt;</a></div>
		<div class="cl"></div>
		<!--<div><img src="images/6.17_08.gif" width="990" height="6" alt=""/></div>-->
	</div>

	<!--内容-->
	<div class="about-us">
		<p>
		西安云际环保科技发展有限公司成立于2018年11月，是一家专业从事环境咨询服务的综合性公司，公司位于西安市新城区解放路77号裕郎国际1幢1321室。
			公司技术队伍实力雄厚，技术员均有大型环评机构的从业经验，专业技术能力过硬。
		公司现有高级工程师2人，中级工程师3人，注册环境影响评价师2人，其他服务人员3人；同时具备完善的计算机网络系统、档案管理系统和
		文件和图档的数字化处理能力，工作质量保证体系健全&nbsp;......
		</p>
	</div>	

</div>

<!--服务项目-->
<div>
	<!--头部-->
	<div class="left-title"><img src="{% static 'web/images/project.gif' %}" width="154" height="25" alt=""/></div>
	<div class="right-title"><a href="{% url 'web:service' %}">更多&nbsp;&gt;&gt;</a></div>
	<div class="cl" style="padding-bottom: 10px;"></div>
	
	<!--内容-->
	<div class="service-content">
		<table width="970" border="0" cellspacing="0" cellpadding="0" style="margin: 10px 10px;">
			<tbody>
				<tr>
					<td width="120"><img src="{% static 'web/images/project01new.jpg' %}" width="120" height="120" alt=""/></td>
					<td width="180" align="left" valign="top">
						<a href="{% url 'web:aboutus' %}" class="service-ah">
							<div class="service-title">环保管家</div>
							<div class="service-miaoshu" style="text-align: justify;">“测、管、治”样样精通，专业提供一站式服务，是能够量身定制解决方案&nbsp;......</div>
							<!--<div class="service-more"><a href="service01.html" >更多 &gt;&gt;</a></div>-->
						</a>
					</td>
					<td width="30" height="120">&nbsp;</td>
					<td width="120"><img src="{% static 'web/images/project02.jpg' %}" width="120" height="120" alt=""/></td>
					<td width="180" align="left" valign="top">
						<a href="{% url 'web:sereva' %}" class="service-ah">
							<div class="service-title">环境影响评价</div>
							<div class="service-miaoshu" style="text-align: justify;">环评是指对规划和建设项目实施后可能造成的环境影响进行分析、预测和评估&nbsp;......</div>
							<!--<div class="service-more"><a href="service02.html" >更多 &gt;&gt;</a></div>-->
						</a>
					</td>
					<td width="30">&nbsp;</td>
					<td width="120"><img src="{% static 'web/images/project03.jpg' %}" width="120" height="120" alt=""/></td>
					<td width="180" align="left" valign="top">
						<a href="{% url 'web:serproduction' %}" class="service-ah">
							<div class="service-title">清洁生产</div>
							<div class="service-miaoshu" style="text-align: justify;">清洁生产是指将综合预防的环境保护策略持续应用于生产过程和产品中&nbsp;......</div>
							<!--<div class="service-more"><a href="service03.html" >更多 &gt;&gt;</a></div>-->
						</a>
					</td>
				</tr>
				<tr>
					<td colspan="8" height="10"></td>
				</tr>
				<tr>
					<td><img src="{% static 'web/images/project04.jpg' %}" width="120" height="120" alt=""/></td>
					<td width="180">
						<a href="{% url 'web:serask' %}" class="service-ah">
							<div class="service-title" style="padding-top:10px;">环保技术资讯</div>
							<div class="service-miaoshu" style="text-align: justify; height: 110px;">为建设项目提供全方位环保技术咨询服务&nbsp;......</div>
							<!--<div class="service-more"><a href="service04.html" >更多 &gt;&gt;</a></div>-->
						</a>
					</td>
					<td height="120">&nbsp;</td>
					<td><img src="{% static 'web/images/project05.jpg' %}" width="120" height="120" alt=""/></td>
					<td width="180">
						<a href="{% url 'web:serdes' %}" class="service-ah">
							<div class="service-title">土壤调查</div>
							<div class="service-miaoshu" style="text-align: justify;">建设用地出现异常点，该如何排查？如何检测地下水？污染检测有哪些要求？针对土壤污染状况调查&nbsp;......</div>
							<!-- <div class="service-more"><a href="service05.html" >更多 &gt;&gt;</a></div> -->
						</a>
					</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
					<td>&nbsp;</td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="web-blank"></div>
</div>

<!--左边栏-->
<div class="left-content">

	<!--成功案例 begin-->
	<!--头部-->
	<div class="title-short-1">
		<div class="left-content-title"><img src="{% static 'web/images/case.gif' %}" width="139" height="25" alt=""/></div>
		<div class="right-content-title"><a href="{% url 'web:category' pk=2 %}">更多&nbsp;&gt;&gt;</a></div>
		<div class="cl"></div>
		<!--<div><img src="images/6.17_16.gif" width="451" height="7" alt=""/></div>-->
	</div>

	<!--内容-->
	<div class="recent-content" style="margin-top:10px;">
		{% get_recent_case_posts as recent_case_list %}
		<ul>
			{% for post in recent_case_list %}
			<a href="{{ post.get_absolute_url }}"><li>
				<span class="list-title">{{ post.title }}</span>
				<span class="list-time">{{ post.created_time.date.year }}/{{ post.created_time.date.month }}/{{ post.created_time.date.day }}</span>
			</li></a>
			{% empty %}
			暂无案例！
			{% endfor %}
		</ul>
		<div class="web-blank"></div>
	</div>
	<!--成功案例 end-->

	<!--文件下载 begin-->
	<!--头部-->
	<div class="title-short-1">
		<div class="left-content-title"><img src="{% static 'web/images/download.gif' %}" width="167" height="25" alt=""/></div>
		<div class="right-content-title"><a href="{% url 'web:category' pk=4 %}">更多&nbsp;&gt;&gt;</a></div>
		<div class="cl"></div>
		<!--<div><img src="images/6.17_16.gif" width="451" height="7" alt=""/></div>-->
	</div>

	<!--内容-->
	<div class="recent-content" style="margin-top:10px;">
		{% get_recent_download_posts as recent_download_list %}
		<ul>
			{% for post in recent_download_list %}
			<a href="{{ post.get_absolute_url }}"><li>
				<span class="list-title">{{ post.title }}</span>
				<span class="list-time">{{ post.created_time.date.year }}/{{ post.created_time.date.month }}/{{ post.created_time.date.day }}</span>
			</li></a>
			{% empty %}
			暂无下载！
			{% endfor %}
		</ul>
		<div class="web-blank"></div>
	</div>
	<!--文件下载 end-->

</div>
	
<!--右边栏-->
<div class="right-content">

	<!--行业资讯 begin-->
	<!--头部-->
	<div class="title-short-2">
		<div class="left-content-title"><img src="{% static 'web/images/information.gif' %}" width="187" height="25" alt=""/></div>
		<div class="right-content-title"><a href="{% url 'web:category' pk=3 %}">更多&nbsp;&gt;&gt;</a></div>
		<div class="cl"></div>
		<!--<div><img src="images/6.17_16.gif" width="500" height="7" alt=""/></div>-->
	</div>
	
	<!--内容-->	
	<div class="recent-content" style="margin-top:10px;">
		{% get_recent_information_posts as recent_information_list %}
		<ul>
			{% for post in recent_information_list %}
			<li>
				<a href="{{ post.get_absolute_url }}">
					<span class="list-title">{{ post.title }}</span>
					<span class="list-time">{{ post.created_time.date.year }}/{{ post.created_time.date.month }}/{{ post.created_time.date.day }}</span>
				</a>
			</li>
			{% empty %}
			暂无资讯！
			{% endfor %}
		</ul>
	</div>
	<!--行业资讯 end-->
	
	<!--友情链接 begin-->
	<div>
		<table width="100%" border="0" cellspacing="0" cellpadding="0" style="padding-left:7px; padding-right: 5px;">
			<tbody>
				<tr>
					<td colspan="5" height="20"></td>
				</tr>
				<tr>
					<td width="150" height="50"><a href="http://www.china-eia.com/" target="_blank"><img src="{% static 'web/images/link01.jpg' %}" width="150" height="50" alt=""/></a></td> 
					<td width="20"></td>
					<td width="150"><a href="http://permit.mee.gov.cn/" target="_blank"><img src="{% static 'web/images/link02.jpg' %}" width="150" height="50" alt=""/></a></td>
					<td width="20"></td>
					<td width="150"><a href="https://www.cenews.com.cn/" target="_blank"><img src="{% static 'web/images/link03.jpg' %}" width="150" height="50" alt=""/></a></td>
				</tr>
				<tr>
					<td colspan="5" height="10"></td>
				</tr>
				<tr>
					<td height="50"><a href="http://www.huanbaogj.cn/" target="_blank"><img src="{% static 'web/images/link04.jpg' %}" width="150" height="50" alt=""/></a></td>
					<td>&nbsp;</td>
					<td><a href="http://www.mee.gov.cn/" target="_blank"><img src="{% static 'web/images/link05.jpg' %}" width="150" height="50" alt=""/></a></td>
					<td>&nbsp;</td>
					<td><a href="http://www.caepi.org.cn/" target="_blank"><img src="{% static 'web/images/link06.jpg' %}" width="150" height="50" alt=""/></a></td>
				</tr>
			</tbody>
		</table>
	</div>
	<!--友情链接 end-->

</div>
		
{% endblock main %}

templates/web/serask.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load web_tags %}

{% block main %}		

<!-- 轮播图片-->
<div class="photo-box">
	<ul class="photo-ul" id="photo-ul" style="list-style: none; margin: 0; padding: 0;"> 
		<li><img src="{% static 'web/images/photo-box01.jpg' %}" width="1000" height="314" /></li>
	</ul>
</div>

<!--左边导航栏-->
<div class="oleft-nav">
    <div class="oleft-width">
        <div class="oleft-title">服务项目</div>
        <ul class="oleft-nav-item" style="position:relative; margin:0px;padding:0px;">
            <li><a href="{% url 'web:service' %}">环保管家</a></li>
            <li><a href="{% url 'web:sereva' %}">环境影响评价、竣工环境保护验收</a></li>
            <li><a href="{% url 'web:serproduction' %}">清洁生产</a></li>
            <li><a id='adivInit' href="{% url 'web:serask' %}">环保技术咨询</a></li>
            <li><a href="{% url 'web:serdes' %}">土壤环境污染调查</a></li>
        </ul>
    </div>
</div>
		
<!---右边内容部分-->
<div class="oright-width">
    <div class="oright-title">网站首页&nbsp;&gt;&nbsp;服务项目&nbsp;&gt;&nbsp;环保技术咨询</div>
    <div class="oright-content">
        <p class="ocontent-main">
            为建设项目提供全方位环保技术咨询服务
        </p>
        <div style="height:300px;"></div>
    </div>
</div>

{% endblock main %}	

templates/web/serdes.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load web_tags %}

{% block main %}		

<!-- 轮播图片-->
<div class="photo-box">
	<ul class="photo-ul" id="photo-ul" style="list-style: none; margin: 0; padding: 0;"> 
		<li><img src="{% static 'web/images/photo-box01.jpg' %}" width="1000" height="314" /></li>
	</ul>
</div>

<!--左边导航栏-->
<div class="oleft-nav">
    <div class="oleft-width">
        <div class="oleft-title">服务项目</div>
        <ul class="oleft-nav-item" style="position:relative; margin:0px;padding:0px;">
            <li><a href="{% url 'web:service' %}">环保管家</a></li>
            <li><a href="{% url 'web:sereva' %}">环境影响评价、竣工环境保护验收</a></li>
            <li><a href="{% url 'web:serproduction' %}">清洁生产</a></li>
            <li><a href="{% url 'web:serask' %}">环保技术咨询</a></li>
            <li><a id='adivInit' href="{% url 'web:serdes' %}">土壤环境污染调查</a></li>
        </ul>
    </div>
</div>

<!---右边内容部分-->
<div class="oright-width">
    <div class="oright-title">网站首页&nbsp;&gt;&nbsp;服务项目&nbsp;&gt;&nbsp;土壤环境污染调查</div>
    <div class="oright-content">
        <p class="ocontent-main">
            建设用地出现异常点，该如何排查？如何检测地下水？污染检测有哪些要求？针对土壤污染状况调查出现的相关问题，市生态环境局日前出台
            专门指引，进一步指导和规范全市土壤污染状况调查相关工作，保障我市建设用地再开发利用环境安全。根据“谁开发，谁保护，谁污染，谁治
            理”原则，污染地块的土壤环境调查和风险评估、风险管控或治理与修复及其效果评估等相关工作，由地块土地使用权人委托第三方开展，生态
            环境部门加强指导服务，并积极引导土壤污染防治第三方市场发展。在第三方市场对建设用地土壤污染状况调查过程中，出现了隐患排查、风
            险评估、地下水采用等问题，不利于准确、完整地作出土壤污染状况评估报告。
        </p>
        <div style="height:300px;"></div>
    </div>
</div>

{% endblock main %}	